image: node:16.13.2-alpine3.14

stages:
  - test
  - deploy

TestValidatingForMR:
  stage: test
  script:
  - yarn install
  - yarn build
  except:
    - main


DeployPage:
  stage: deploy
  script:
  - yarn install
  - yarn build
  - mv ./build ../public
  artifacts:
    paths:
    - public
  only:
    - main