image: node:16.13.2-alpine3.14

stages:
  - test
  - deploy

test:
  stage: test
  script:
    #- cd telescope
    - yarn install
    - yarn build
  except:
    - main

pages:
  stage: deploy
  script:
    #- cd telescope
    - yarn install
    - yarn build
    - mv ./build ./public
  #- mv ./build ../public
  artifacts:
    paths:
      - public
  only:
    - main
